### ISSUE TITLE
:기능:나갔다오실 것을 추천드립니다

### ISSUE THREAD

**Issue by eolgaeng-i** [JMmmmuu/YUSEOK_Blog#3]

**Comment by Walkers15** [comment]
이슈 다는거 개꿀잼 꺄륵

**Comment by JMmmmuu** [comment]
@eolgaeng-i @Walkers15 
해당 이슈 해결된 것으로 확인되어 닫습니다!
친구없는 절 위해 앞으로 이슈 많이 달아주쎄여!! ㅋㅋㅋㅋㅋㅋㅋㅋ
